import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.scss';
import { API_HOST } from '../../services/constants';
import Content from '../Content';
import Splash from '../Splash';

export async function getServerSideProps() {

  const res = await fetch(`${API_HOST}/api/page-data`);
  console.log(API_HOST);
  const pageData = await res.json();

  return {
    props: {
      ...pageData
    }
  }
}

  // TO DO: COMPONENTIZE FOOTER, HEAD
  // SHAPE DATA INTO HEAD, CONTENT, FOOTER
  // MENU WILL ALSO BE ITS OWN CONTENT ON TOP OF CONTENT, SO 4 MAIN DATA OBJECTS

const Page = (props: any) => {

  return (
    <div>
      <Head>
        <title>CMS Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Content {...props} />   

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Page
