import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.scss';
import Content from '../Content';
import Footer from '../Footer';

  // TO DO: COMPONENTIZE FOOTER, HEAD
  // SHAPE DATA INTO HEAD, CONTENT, FOOTER
  // MENU WILL ALSO BE ITS OWN CONTENT ON TOP OF CONTENT, SO 4 MAIN DATA OBJECTS

const Page = (props: any) => {

  const {contentType} = props;

  return (
    <div>
      <Head>
        <title>CMS Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Content {...props} />   

      <Footer contentType={contentType} />
    </div>
  )
}

export default Page
