import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useRouter } from 'next/router';
import { API_HOST } from '../services/constants';
import Splash from '../components/Splash';

export async function getServerSideProps() {

  const res = await fetch(`${API_HOST}/api/page-data`);
  console.log(API_HOST);
  const pageData = await res.json();

  return {
    props: {
      ...pageData
    }
  }
}

const Page = (props: any) => {

  // Add container with switch statement for page type

  return (
    <div>
      <Head>
        <title>CMS Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Splash {...props}/>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Page
