import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';

const dev = process.env.NODE_ENV !== 'production';

export const server = dev ? 'http://localhost:3000' : process.env.VERCEL_URL;

export async function getStaticProps() {

  const res = await fetch(`${server}/api/page-data`);
  const pageData = await res.json();

  return {
    props: {
      ...pageData
    }
  }
}

const Home = (props: any) => {

  const { topContent, backgroundImage } = props;

  return (
    <div>
      <Head>
        <title>CMS Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >

        {documentToReactComponents(topContent)}
        <div>
          <Image 
            src={`https:${backgroundImage?.file?.url}`} 
            alt={backgroundImage?.description} 
            layout="fill"
            objectFit="cover"
            />
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
